### ISSUE TITLE
virtualenv error

### ISSUE THREAD

**Issue by alexflint** [OpenBazaar/OpenBazaar-Installer#8]
I'm seeing the following error when I try to build the OSX installer:

```
$ sh make_openbazaar.sh osx
make_openbazaar.sh: line 1: ﻿﻿#!/bin/sh: No such file or directory
Cloning OpenBazaar-Server
Where do you wish to clone OpenBazaar-Server to? [OpenBazaar-Server] 
Directory OpenBazaar-Server already exists, do you wish to delete it and redownload? (yes/no) [no] 
Directory already exists and you've chosen not to clone again
Cloning OpenBazaar-Client
Where do you wish to clone OpenBazaar-Client to? [OpenBazaar-Client] 
Directory OpenBazaar-Client already exists, do you wish to delete it and redownload? (yes/no) [no] 
Directory already exists and you've chosen not to clone again
Do you wish to install the required dependencies for OpenBazaar and setup for building? (yes/no) [yes] 
Switched to /Users/alex/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client
Installing global dependencies
Password:
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
Global dependencies installed successfully!
Installing local dependencies
Local dependencies installed successfully!
Local permissions corrected successfully!
Successfully setup for OpenBazaar
Building OS X binary
cp: directory build does not exist
mkdir: OpenBazaar-Client: No such file or directory
make_openbazaar.sh: line 328: cd: OpenBazaar-Server: No such file or directory
Using base prefix '/Applications/anaconda'
New python executable in env/bin/python3
Not overwriting existing python script env/bin/python (you must use env/bin/python3)
ERROR: The executable env/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/Users/alex/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client' (should be '/Users/alex/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/env')
ERROR: virtualenv is not compatible with this system or executable
make_openbazaar.sh: line 330: env/bin/activate: No such file or directory
```

**Comment by alexflint** [comment]
For a start, the first line of `make_openbazaar.sh` seems to have whitespace ahead of the `#!`

**Comment by hoffmabc** [comment]
Hmm I will take a look.

**Comment by hoffmabc** [comment]
ok @alexflint try now. I committed some updates to the repo that were causing issues. Not sure if it will fix all of yours but let's try it.

**Comment by stevenroose** [comment]
I got this error as well in Fedora 22. I tried installing all `python*-virtualenv*` packages, but the error persisted.

**Comment by hoffmabc** [comment]
@stevenroose have you tried the latest version of the code?

**Comment by stevenroose** [comment]
I did that with the latest version at the time I made the issue.. Did you
push something new?

**Comment by stevenroose** [comment]
It works when I replace all occurences of `virtualenv2` with just `virtualenv`.

**Comment by skecskes** [comment]
I git cloned release 1.1.0 and run installer on OSX. It stopped here for me

```
Creating virtualenv and building OpenBazaar-Server binary...
./make_openbazaar.sh: line 276: virtualenv: command not found
./make_openbazaar.sh: line 277: env/bin/activate: No such file or directory
```
